# -*- coding: utf-8 -*-
"""Consumer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WyORi_fgmVfDD_8LMi6FXUuSt5k0R79m

Librerie
"""

from kafka import KafkaConsumer
from pymongo import MongoClient
import time
import json

consumer = KafkaConsumer(bootstrap_servers=["localhost:9092"], #auto_offset_reset='earliest', 
                         consumer_timeout_ms=1000)

consumer.subscribe('LCDP') #Nome topic Kafka

client = MongoClient('localhost', 27017)
db = client.Progetto #nome DB Mongo

while(True): 
    for tweets in consumer: 
        tweet = json.loads(tweets.value) 
        result = db.Progetto.insert_one(tweet) #NomeDBMongo
        time.sleep(5)